### ISSUE TITLE
Executing Issue

### ISSUE THREAD

**Issue by SIDDHARTH2306** [blacksteed232/trafficMonitorPrototype#10]
When I simply run your code it just goes to exception part and prints EOF.
I tried removing try block and checked the error. I countered some errors but at last I am failing with the solution.
It gives me 3 types of error.

![capture](https://user-images.githubusercontent.com/20282898/43368986-95121308-9383-11e8-9ba9-b76b4ab16b2e.PNG)

**Comment by AlexBlack2202** [comment]
@SIDDHARTH2306  replace long to int
