### ISSUE TITLE
 error: (-215) dims <= 2 && step[0] > 0 in function locateROI

### ISSUE THREAD

**Issue by mishra011** [blacksteed232/trafficMonitorPrototype#2]
Hey, 
I am trying to run this code on my laptop and I am getting error:( error: (-215) dims <= 2 && step[0] > 0 in function locateROI). Can you help me out. I am using Ubuntu 14.04 , python 2.7 and opencv3.1.
## error is as follows:
 fgmask = cv2.blur(frame, (10,10))
cv2.error: /home/deepak/ENV/opencv-3.2.0/modules/core/src/matrix.cpp:949: error: (-215) dims <= 2 && step[0] > 0 in function locateROI

**Comment by akphi** [comment]
hey @mishra011 
Do you use the same video that I use as the source file? I suspect that since that what I found in this [thread](https://stackoverflow.com/questions/31758384/cverode-causes-error-opencv-error-assertion-failed-m-dims-2-in-mat). That should not matter but try that just in case. Also, try with Python 2.7.12. Last but not least, I have been looking around for [advice](https://www.experts-exchange.com/questions/26929630/Assertion-Failed-on-LocateRoi-with-OpenCV.html) on this matter since I personally cannot reproduce the bug... It would be great if you can tell me which line of the code caused this problem.

**Comment by mishra011** [comment]
Thanks for reaching out to me. Finally, your code is running. The problem was in the VideoCapture(). I found that cap.isOpened() was returning false. Then I uninstalled opencv and reinstalled it, and it worked.

**Comment by akphi** [comment]
@mishra011 Thanks for finding out the bug!

**Comment by mishra011** [comment]
Hey,
I was testing you code on a video recorded with my mobile and it worked OK
after I changed max and min area and line coordinates.
1) Please tell me that what are the parameters needed to modeled to get it
working.
2) Why it is not working if a person is already present in a video from
first frame.
3)What does getExteriorRect method do?
Any help will be appreciated.

Regards
Deepak Mishra

On Jun 1, 2017 2:42 AM, "An Phi" <notifications@github.com> wrote:

Closed #2 <https://github.com/blacksteed232/PedestrianCounter/issues/2>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blacksteed232/PedestrianCounter/issues/2#event-1104972910>,
or mute the thread

**Comment by akphi** [comment]
@mishra011 I didn't quite get what you meant in the first question. For the second question, the 2 major techniques are backgroundSubtractorMOG, which compares a frame with what the -so-called background. Usually, people create a background out of the first few empty frame of the video (you can think of this as the beginning of the day and nobody has passed the camera vision yet). For tracking, I used meanShift, which I believe bases on frame subtraction, but this sits on top of MOG so I guess MOG is the main culprit.
For the third point, getExteriorRect outputs points to draw a rectangle around the "thought-to-be" moving person (I believe this is for me to output the snapshot of the violating pedestrian),

**Comment by SenthilVikram** [comment]
I previously encountered the same problem. Then I realized that my image file path is misspelled. In my code, an image file was named "note.jpg" and in my directory, it was "note.jpg.jpg" and instead of "j.jpg" I wrote it as "j.png". After recorrecting them, everything went well.
