### ISSUE TITLE
Please help me fix the bug as attached!

### ISSUE THREAD

**Issue by biencuong** [blacksteed232/trafficMonitorPrototype#5]
Please help me fix the bug as attached!
![20542979_1961182707451600_940043185_o](https://user-images.githubusercontent.com/26410999/28767310-57e8fdc4-75fd-11e7-9e1d-c5f74be28770.jpg)

Thanks!

**Comment by akphi** [comment]
@biencuong  Seems like your version of OpenCV does not have this function. Can you check that you are using Open CV 3.1.0 as indicated in the README file?
