### ISSUE TITLE
consult  for  the  steps  to  run  the code?

### ISSUE THREAD

**Issue by wn312991** [blacksteed232/trafficMonitorPrototype#6]
hello,could  you  tell me  the  steps to  run the  code? thanks you

**Comment by akphi** [comment]
@wn13083405221 Sure! Here is a rough guide.
1. Download the video, make sure you put it in the same directory as the source code.
2. Make sure you installed Python (I think I used python 3)
3. Install OpenCV 3.1 (probably the hardest step, but you can find a guide online to tell you. I think I followed the [guide](https://www.pyimagesearch.com/2015/06/29/install-opencv-3-0-and-python-3-4-on-osx/) of Adrian, by the way, he's a super passionate and smart guide, totally visit his website and crunch some of his tutorials!)
4. Run the file in terminal:  ```python3 traffic.py```

Good luck!
