### ISSUE TITLE
how to change count regioin

### ISSUE THREAD

**Issue by kksu49** [blacksteed232/trafficMonitorPrototype#7]
For Example: in the code it count people in and out by divide it to top and button part. How can I change it. such as left and right, or any other direction.

**Comment by kksu49** [comment]
at line 224, there is a boundarypart1  boundarypart2,  when change the value the green line changes with it.  is that all I need to do  ?

**Comment by akphi** [comment]
@kksu49 please check the checkPosition() function at line 166
