### ISSUE TITLE
consult  for  the   environment   and  the  steps  to  run  the  code?

### ISSUE THREAD

**Issue by wn312991** [blacksteed232/trafficMonitorPrototype#8]
consult  for  the   environment   and  the  steps  to  run  the  code? thanks you

**Comment by akphi** [comment]
Hi, @wn13083405221 could you refer to [this](https://github.com/blacksteed232/PedestrianCounter/issues/6)? To be honest, I was quite a novice back then, so no complicated things required other than setting up OpenCV and Python correctly. I coded this on Linux, using Python 3 and OpenCV 3.1.0 (at that time, the steps to install 3.1.0 was not really easy to follow). Hope that helps!
